package sh.omni.domain.ports;

import org.apache.pdfbox.pdmodel.font.Standard14Fonts;

/**
 * Defines a set of constant values used for PDF generation and formatting.
 * These constants provide default settings for font size, font type, margins,
 * and line spacing, ensuring consistency in PDF documents generated by classes
 * that implement or rely on this interface.

 * Constants:
 * - DEFAULT_FONT_SIZE: Specifies the default font size for text in the PDF.
 * - DEFAULT_FONT: Specifies the default font type for text in the PDF, based on PDFBox Standard14 fonts.
 * - DEFAULT_MARGIN_LEFT: Specifies the left margin for content in the PDF.
 * - DEFAULT_MARGIN_TOP: Specifies the top margin for content in the PDF.
 * - DEFAULT_LINE_SPACING: Specifies the default spacing between lines of text in the PDF.
 */
public interface IPdfConstants {
      float DEFAULT_FONT_SIZE = 12f;
      Standard14Fonts.FontName DEFAULT_FONT = Standard14Fonts.FontName.HELVETICA;
      float DEFAULT_MARGIN_LEFT = 50f;
      float DEFAULT_MARGIN_TOP = 700f;
      float DEFAULT_LINE_SPACING = -15f;
}
